name: Checksum builder Windows

on:
  push:
    #    branches:
    #      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
      - name: compile
        run: go build checksum.go
      - name: Test
        run: |
          touch file
          echo 1  >> file
          .\checksum.exe -s sha256 -f file
          .\checksum.exe -s sha256 -f checksum.exe > checksum.sha256
      - name: Upload to checksum binary to github
        uses: actions/upload-artifact@v3
        with:
          name: checksum_win
          path: |
            checksum.exe
            checksum.sha256
