# This file updates the NUSPEC(s) in the repo checking the API

name: Checksum builder

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with :
          go-version: 'stable'
          check-latest: true  
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: compile 
        run: go build checksum.go
  validate: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          touch file
          echo 1  >> file
          ./checksum -c sha256 -f file 
